server:
  port: 0
  servlet:
    context-path: /mails

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        listenMessages-in-0.destination: mails
      binder:
        brokers: localhost:9092
  zipkin:
    baseUrl: http://127.0.0.1:9411/
